// AUTO-GENERATED by scripts/generate-present-assets.mjs
// Lists known static assets as extensionless bases for <AssetImage/> and <VideoPlayer/>

export const partners = [];
export const ideonautixPreviews = [
  "/images/ideonautix/ideonautix-icon"
];
export const nodevoyagePreviews = [
  "/images/nodevoyage/nodevoyage-icon"
];

export const videoAlgorhythmics = "/videos/algorhythmics-promo";
export const videoIdeonautix   = "/videos/ideonautix-promo";
export const videoNodeVoyage   = "/videos/nodevoyage-promo";
