name: Deploy (OSS)
on:
  push: { branches: [ main ] }
  workflow_dispatch:
permissions: { contents: read }
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: 'npm' }
      - run: npm ci
      - run: npm run build
      - name: Download ossutil
        run: |
          curl -L http://gosspublic.alicdn.com/ossutil/1.7.17/ossutil64 -o ossutil64
          chmod +x ossutil64
      - name: Configure ossutil
        env:
          OSS_ACCESS_KEY_ID:     ${{ secrets.OSS_ACCESS_KEY_ID }}
          OSS_ACCESS_KEY_SECRET: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
          OSS_ENDPOINT:          ${{ secrets.OSS_ENDPOINT }}
        run: ./ossutil64 config -i "$OSS_ACCESS_KEY_ID" -k "$OSS_ACCESS_KEY_SECRET" -e "$OSS_ENDPOINT" -L CH
      - name: Sync build → OSS
        env: { OSS_BUCKET: ${{ secrets.OSS_BUCKET }} }
        run: ./ossutil64 cp -r build/ oss://$OSS_BUCKET/ -f --meta="Cache-Control:no-cache"
      - name: (Optional) Purge CDN
        if: ${{ secrets.ALICLOUD_ACCESS_KEY_ID && secrets.ALICLOUD_ACCESS_KEY_SECRET && secrets.ALICLOUD_CDN_DOMAIN }}
        env:
          AK: ${{ secrets.ALICLOUD_ACCESS_KEY_ID }}
          SK: ${{ secrets.ALICLOUD_ACCESS_KEY_SECRET }}
          DOMAIN: ${{ secrets.ALICLOUD_CDN_DOMAIN }}
        run: |
          echo "TODO: integrate aliyun CDN RefreshObjectCaches for https://$DOMAIN/*"
          # For production, use the official aliyun CLI or API here.
