name: Preview (Alibaba OSS)
on:
  pull_request: { types: [opened, synchronize, reopened] }
permissions:
  contents: read
  pull-requests: write
jobs:
  preview-oss:
    if: ${{ secrets.OSS_BUCKET_PREVIEW }}
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: 'npm' }
      - run: npm ci
      - run: npm run build
      - name: Get ossutil
        run: |
          curl -L http://gosspublic.alicdn.com/ossutil/1.7.17/ossutil64 -o ossutil64
          chmod +x ossutil64
      - name: Configure ossutil
        env:
          OSS_ACCESS_KEY_ID:     ${{ secrets.OSS_ACCESS_KEY_ID }}
          OSS_ACCESS_KEY_SECRET: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
          OSS_ENDPOINT:          ${{ secrets.OSS_ENDPOINT }}
        run: ./ossutil64 config -i "$OSS_ACCESS_KEY_ID" -k "$OSS_ACCESS_KEY_SECRET" -e "$OSS_ENDPOINT" -L CH
      - name: Upload to preview path
        id: up
        env:
          BUCKET: ${{ secrets.OSS_BUCKET_PREVIEW }}
          PR: ${{ github.event.number }}
          SHA: ${{ github.sha }}
        run: |
          ./ossutil64 cp -r build/ oss://$BUCKET/pr-$PR/ -f --meta="Cache-Control:no-cache"
          echo "url=https://$BUCKET.${{ secrets.OSS_ENDPOINT }}/pr-$PR/index.html" >> $GITHUB_OUTPUT
      - name: Comment URL
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: preview-oss
          message: |
            ✅ OSS preview: **${{ steps.up.outputs.url }}**
            _Path: `oss://${{ secrets.OSS_BUCKET_PREVIEW }}/pr-${{ github.event.number }}/`_
