name: Preview (Netlify)
on:
  pull_request: { types: [opened, synchronize, reopened] }
permissions:
  contents: read
  pull-requests: write
jobs:
  preview:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: 'npm' }
      - run: npm ci
      - run: npm run build
      - name: Install Netlify CLI
        run: npm i -g netlify-cli
      - name: Deploy draft preview
        id: nl
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          out=$(netlify deploy --dir=build --json --message "PR #${{ github.event.number }}")
          echo "$out" | jq .
          echo "url=$(echo "$out" | jq -r '.deploy_url')" >> $GITHUB_OUTPUT
      - name: Comment URL
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: preview
          message: |
            ✅ Netlify preview: **${{ steps.nl.outputs.url }}**
            _Auto-updates on pushes to this PR._
