name: Stale
on: { schedule: [ { cron: "0 1 * * *" } ] }
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 30
          days-before-close: 7
          stale-issue-message: "Inactive for 30 days. Comment to keep open."
          stale-pr-message: "This PR is idle. Please push updates or comment."
          exempt-issue-labels: "pinned,security"
